name: grex_ds
description: Grex Design System for Flutter.
version: 0.1.11
homepage: https://grex.com.br
repository: https://github.com/grex-corp/grex_ds_flutter

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  image_cropper: ^11.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  shimmer: ^3.0.0
  rounded_loading_button_plus: ^3.0.1
  delightful_toast: ^1.1.0
  intl: ^0.20.2
  flutter_svg: ^2.0.17
  linkify: ^5.0.0
  url_launcher: ^6.3.1
  mask_text_input_formatter: ^2.9.0
  popover: ^0.4.0
  infinite_scroll_pagination: ^5.0.0
  flutter_libphonenumber: ^2.4.0
  device_info_plus: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/flags/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Thin.otf
          weight: 100
        - asset: fonts/Montserrat/ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/Montserrat/ExtraLight.otf
          weight: 200
        - asset: fonts/Montserrat/ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/Montserrat/Light.otf
          weight: 300
        - asset: fonts/Montserrat/LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/Montserrat/Regular.otf
          weight: 400
        - asset: fonts/Montserrat/RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/Montserrat/Medium.otf
          weight: 500
        - asset: fonts/Montserrat/MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/Montserrat/SemiBold.otf
          weight: 600
        - asset: fonts/Montserrat/SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/Montserrat/Bold.otf
          weight: 700
        - asset: fonts/Montserrat/BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/Montserrat/ExtraBold.otf
          weight: 800
        - asset: fonts/Montserrat/ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: fonts/Montserrat/Black.otf
          weight: 900
        - asset: fonts/Montserrat/BlackItalic.otf
          weight: 900
          style: italic
    - family: GrxIcons
      fonts:
        - asset: fonts/GrxIcons/GrxIcons.ttf
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
